wangyuhanhhh/curriculum

web/src/app/school/school.module.ts
web/src/app/term/add/add.component.ts

feat:  when add success it will be navigate termlist

---

htdocs/thinkphp5/application/index/controller/TermController.php
web/src/app/entity/term.ts
web/src/app/term/add/add.component.html
web/src/app/term/add/add.component.ts
web/src/app/term/edit/edit.component.html
web/src/app/term/edit/edit.component.ts
web/src/app/term/term.component.html

修改term中的一些字段：fix some name

---

htdocs/thinkphp5/application/common/model/Teacher.php
htdocs/thinkphp5/application/index/controller/TeacherController.php
web/src/app/app-routing.module.ts
web/src/app/app.component.html
web/src/app/app.module.ts
web/src/app/entity/teacher.spec.ts
web/src/app/entity/teacher.ts
web/src/app/teacher/teacher.component.css
web/src/app/teacher/teacher.component.html
web/src/app/teacher/teacher.component.spec.ts
web/src/app/teacher/teacher.component.ts
web/src/app/teacher/teacher.module.ts
web/src/service/teacher.service.spec.ts
web/src/service/teacher.service.ts

feat: teacher list

---

web/src/app/app.component.css
web/src/app/app.component.html

1、实现导航栏的随机点亮
2、修改路由，是页面导航右边的内容随路由变化而变化

fix:nav active

---

htdocs/thinkphp5/application/common/validate/StudentValidate.php
htdocs/thinkphp5/application/index/controller/StudentController.php
web/src/app/entity/user.ts
web/src/app/user/add/add.component.html
web/src/app/user/add/add.component.ts
web/src/service/user.service.ts

修改学生用户的新增逻辑，在新增学生的时候，同时新增user数据；
同时，将student表中的password放在了user表中；
修改了一下，User.service中的类型规定

fix:student add

---

htdocs/thinkphp5/application/index/controller/ClazzController.php
web/src/app/app-routing.module.ts
web/src/app/clazz/clazz.component.html
web/src/app/clazz/clazz.component.ts
web/src/app/clazz/clazz.module.ts
web/src/app/clazz/page/page.component.html
web/src/app/clazz/page/page.component.spec.ts
web/src/app/clazz/page/page.component.ts
web/src/app/clazz/page/page.module.ts
web/src/app/entity/page.spec.ts
web/src/app/entity/page.ts
web/src/service/clazz.service.ts

实现班级页面分页，完成分页组件。由于只需要进行简单的数据交互，不用双向绑定，所以使用@input@output进行父子组件的通信

67 pageComponent clazz page

---

htdocs/thinkphp5/application/common/model/Student.php
htdocs/thinkphp5/application/index/controller/StudentController.php
web/src/app/entity/user.ts
web/src/app/user/add/add.component.html
web/src/app/user/clazz-select/clazz-select.component.ts
web/src/app/user/edit/edit.component.html
web/src/app/user/edit/edit.component.ts

1、修改学生编辑，确保 student 数据和 user 数据同步更改（通过启用事务）
2、修改了编辑页面，使学校不能被修改，只能修改班级

fix:student edit

---

htdocs/thinkphp5/application/common/model/Term.php
htdocs/thinkphp5/application/index/controller/SchoolController.php
htdocs/thinkphp5/application/index/controller/StudentController.php
htdocs/thinkphp5/application/index/controller/TeacherController.php
htdocs/thinkphp5/application/index/controller/TermController.php
web/src/app/clazz/clazz.component.ts
web/src/app/clazz/page/page.component.html
web/src/app/clazz/page/page.component.ts
web/src/app/clazz/page/page.module.ts
web/src/app/entity/term.ts
web/src/app/entity/user.ts
web/src/app/school/school.component.html
web/src/app/school/school.component.ts
web/src/app/school/school.module.ts
web/src/app/teacher/teacher.component.html
web/src/app/teacher/teacher.component.ts
web/src/app/teacher/teacher.module.ts
web/src/app/term/term.component.html
web/src/app/term/term.component.ts
web/src/app/term/term.module.ts
web/src/app/user/user.component.html
web/src/app/user/user.component.ts
web/src/app/user/user.module.ts
web/src/service/school.service.ts
web/src/service/teacher.service.ts
web/src/service/term.service.ts
web/src/service/user.service.ts

80 global use page

---

htdocs/thinkphp5/application/index/controller/TeacherController.php
web/src/app/teacher/teacher.component.html
web/src/app/teacher/teacher.component.ts
web/src/service/teacher.service.ts

重构分页方法，使其支持搜索和分页。删除了 teacher.service 中的 page API 已经后台的 page 方法。查询和分页都对应后台的 search 方法

fix:整合查询和分页功能，通用分页加载方法，支持搜索和分页

---

htdocs/thinkphp5/application/index/controller/ClazzController.php
web/src/app/clazz/clazz.component.css
web/src/app/clazz/clazz.component.html
web/src/app/clazz/clazz.component.ts
web/src/app/clazz/clazz.module.ts
web/src/app/teacher/teacher.component.ts
web/src/service/clazz.service.ts

feat:支持搜索的分页功能

---

htdocs/thinkphp5/application/index/controller/TermController.php
web/src/app/school/school.component.html
web/src/app/term/term.component.css
web/src/app/term/term.component.html
web/src/app/term/term.component.ts
web/src/app/term/term.module.ts
web/src/service/term.service.ts

feat:学期的分页查询

---

htdocs/thinkphp5/application/index/controller/StudentController.php
web/src/app/clazz/clazz.component.html
web/src/app/term/term.component.html
web/src/app/user/user.component.css
web/src/app/user/user.component.html
web/src/app/user/user.component.ts
web/src/app/user/user.module.ts
web/src/service/user.service.ts

feat:学生页面的分页查询（以姓名和学号为查询条件）

---

htdocs/thinkphp5/application/common/model/Clazz.php
htdocs/thinkphp5/application/common/model/Teacher.php
htdocs/thinkphp5/application/common/validate/ClazzValidate.php
htdocs/thinkphp5/application/index/controller/ClazzController.php
htdocs/thinkphp5/application/index/controller/TeacherController.php
web/src/app/clazz/clazz.component.html
web/src/app/clazz/clazz.component.ts
web/src/app/clazz/clazz.module.ts
web/src/app/clazz/edit/edit.component.ts
web/src/app/clazz/head-teacher/head-teacher.component.html
web/src/app/clazz/head-teacher/head-teacher.component.spec.ts
web/src/app/clazz/head-teacher/head-teacher.component.ts
web/src/app/clazz/teacher-select/teacher-select.component.css
web/src/app/clazz/teacher-select/teacher-select.component.html
web/src/app/clazz/teacher-select/teacher-select.component.spec.ts
web/src/app/clazz/teacher-select/teacher-select.component.ts
web/src/app/clazz/teacher-select/teacher-select.module.ts
web/src/app/entity/clazz.ts
web/src/service/clazz.service.ts
web/src/service/teacher.service.ts

feat:设置班主任

---

htdocs/thinkphp5/application/index/controller/ClazzController.php
htdocs/thinkphp5/application/index/controller/SchoolController.php
web/src/app/entity/school.ts
web/src/app/entity/term.ts
web/src/app/school/admin/admin.component.css
web/src/app/school/admin/admin.component.html
web/src/app/school/admin/admin.component.spec.ts
web/src/app/school/admin/admin.component.ts
web/src/app/school/school.component.html
web/src/app/school/school.component.ts
web/src/app/school/school.module.ts
web/src/service/school.service.ts

feat:为学校设置管理员

---

htdocs/thinkphp5/application/index/controller/IndexController.php
htdocs/thinkphp5/application/index/controller/LoginController.php
htdocs/thinkphp5/application/index/controller/UserController.php
web/src/app/app-routing.module.ts
web/src/app/app.module.ts
web/src/app/entity/person.spec.ts
web/src/app/entity/person.ts
web/src/app/layout/header/header.component.css
web/src/app/layout/header/header.component.html
web/src/app/layout/header/header.component.spec.ts
web/src/app/layout/header/header.component.ts
web/src/app/layout/layout.component.html
web/src/app/layout/nav/nav.component.html
web/src/app/personal-center/personal-center.component.css
web/src/app/personal-center/personal-center.component.html
web/src/app/personal-center/personal-center.component.spec.ts
web/src/app/personal-center/personal-center.component.ts
web/src/service/login.service.ts
web/src/service/person.service.spec.ts
web/src/service/person.service.ts

feat:完成了个人中心的页面、登出功能，同时封装了整体页面的头部

---

htdocs/thinkphp5/application/common/model/Course.php
htdocs/thinkphp5/application/common/model/CourseInfo.php
htdocs/thinkphp5/application/index/controller/CourseController.php
web/src/app/app-routing.module.ts
web/src/app/clazz/clazz.component.ts
web/src/app/course/course.component.css
web/src/app/course/course.component.html
web/src/app/course/course.component.spec.ts
web/src/app/course/course.component.ts
web/src/app/course/course.module.ts
web/src/app/entity/course.spec.ts
web/src/app/entity/course.ts
web/src/app/layout/nav/nav.component.html
web/src/app/school/school.component.ts
web/src/service/course.service.spec.ts
web/src/service/course.service.ts

feat:课程管理列表初始化

---

htdocs/thinkphp5/application/index/controller/CourseController.php
web/src/app/clazz/head-teacher/head-teacher.component.ts
web/src/app/course/add/add.component.css
web/src/app/course/add/add.component.html
web/src/app/course/add/add.component.spec.ts
web/src/app/course/add/add.component.ts
web/src/app/course/course.component.html
web/src/app/course/course.component.ts
web/src/app/course/course.module.ts
web/src/app/dashboard/dashboard.component.html
web/src/app/entity/course.ts
web/src/service/course.service.ts

feat: 课程新增

---

htdocs/thinkphp5/application/index/controller/CourseController.php
web/src/app/course/add/add.component.html
web/src/app/course/add/add.component.ts
web/src/app/course/course.component.html
web/src/app/course/edit/edit.component.html
web/src/app/course/edit/edit.component.ts

fix:修复课程管理分页

---

htdocs/.idea/workspace.xml
htdocs/thinkphp5/application/index/controller/TeacherController.php
web/src/app/clazz/add/add.component.html
web/src/app/entity/teacher.ts
web/src/app/teacher/add/add.component.html
web/src/app/teacher/add/add.component.ts
web/src/app/teacher/edit/edit.component.html
web/src/app/teacher/edit/edit.component.ts
web/src/app/teacher/teacher.component.html
web/src/app/teacher/teacher.module.ts

fix:修改教师的显示列表及新增，编辑方法

---

htdocs/thinkphp5/application/index/controller/CourseController.php
web/src/app/course-table/course-table.component.html
web/src/app/course-table/course-table.component.ts
web/src/app/course/add/add.component.ts
web/src/app/course/edit/edit.component.ts
web/src/app/entity/course-info.ts
web/src/service/course.service.ts

feat:动态渲染学生课表，同时查询功能生效（默认查询当前周的课表）

---

htdocs/.idea/workspace.xml
htdocs/thinkphp5/application/index/controller/ClazzController.php
htdocs/thinkphp5/application/index/controller/TeacherController.php
web/src/app/clazz/clazz.component.html
web/src/app/clazz/clazz.component.ts
web/src/app/clazz/clazz.module.ts
web/src/app/clazz/head-teacher/head-teacher.component.ts
web/src/app/school/school.component.ts
web/src/service/clazz.service.ts
web/src/service/school.service.ts

fix:修改删除教师及设置班主任方法

---

htdocs/thinkphp5/application/index/controller/CourseController.php

bug:修改好了当课程为单周时，查询双周课程不显示

---

htdocs/thinkphp5/application/index/controller/CourseController.php
htdocs/thinkphp5/application/index/controller/TeacherController.php
web/src/app/course-table/course-table.component.html
web/src/app/course-table/course-table.module.ts
web/src/app/course-table/student-schedule/look-all/look-all.component.ts
web/src/app/course-table/teacher-schedule/teacher-schedule.component.css
web/src/app/course-table/teacher-schedule/teacher-schedule.component.html
web/src/app/course-table/teacher-schedule/teacher-schedule.component.spec.ts
web/src/app/course-table/teacher-schedule/teacher-schedule.component.ts
web/src/app/user/clazz-select/clazz-select.component.css
web/src/app/user/clazz-select/clazz-select.module.ts
web/src/app/user/user.module.ts
web/src/service/course.service.ts
web/src/service/teacher.service.ts

点击进入“课表查询”页面，没有默认数据
选择班级后，显示的只是该班级的所有必修课。而不包含学生个人的选修课

feat:实现教师、班主任用户点击课表查询的时候，功能为查看自己学校的个班级的学期总课表

---

htdocs/thinkphp5/application/index/controller/CourseController.php
web/src/app/course-table/admin-schedule/admin-schedule.component.css
web/src/app/course-table/admin-schedule/admin-schedule.component.html
web/src/app/course-table/admin-schedule/admin-schedule.component.spec.ts
web/src/app/course-table/admin-schedule/admin-schedule.component.ts
web/src/app/course-table/course-table.component.html
web/src/app/course-table/course-table.module.ts
web/src/app/entity/course-info.ts
web/src/service/course.service.ts

feat:管理员（包括超管）的课表查询页面

---

htdocs/thinkphp5/application/index/controller/LoginController.php
htdocs/thinkphp5/application/index/controller/StudentController.php
htdocs/thinkphp5/application/index/controller/TeacherController.php
web/src/app/entity/response-body.ts
web/src/app/login/login.component.ts
web/src/interceptor/x-auth-token.interceptor.ts
web/src/service/login.service.ts

fix:解决登录失败弹窗不匹配问题，实现当学生用户被冻结无法登录的功能

---

htdocs/thinkphp5/application/index/controller/DingTalkMsgController.php
htdocs/thinkphp5/application/index/controller/TermController.php

feat：钉钉推送内容初始化，确定了数据的类型

---

web/src/app/clazz/add/add.component.ts
web/src/app/clazz/clazz.component.ts
web/src/app/clazz/edit/edit.component.ts
web/src/app/clazz/head-teacher/head-teacher.component.ts
web/src/app/course-table/course-table.component.ts
web/src/app/course-table/student-schedule/look-all/look-all.component.ts
web/src/app/course-table/teacher-schedule/teacher-schedule.component.ts
web/src/app/entity/user.ts
web/src/app/layout/header/header.component.ts
web/src/app/layout/nav/nav.component.ts
web/src/app/personal-center/personal-center.component.ts
web/src/app/school/add/add.component.ts
web/src/app/school/admin/admin.component.ts
web/src/app/school/edit/edit.component.ts
web/src/app/school/school.component.ts
web/src/app/teacher/add/add.component.ts
web/src/app/teacher/edit/edit.component.ts
web/src/app/teacher/teacher.component.ts
web/src/app/term/add/add.component.ts
web/src/app/term/edit/edit.component.ts
web/src/app/term/term.component.ts
web/src/app/user/add/add.component.ts
web/src/app/user/edit/edit.component.ts
web/src/app/user/user.component.ts
web/src/service/login.service.ts

主要的原因就是，在 login.service 服务中对数据类型的处理不当
上述代码如果不加 else ， 换句话说，将 else 中的代码直接放在 if 语句的后面。就会导致，解析后的 user 会被覆盖（如下时错误代码）

bug：解决了每次登录时控制台的数据类型报错

---

web/src/app/course-table/admin-schedule/admin-schedule.component.html
web/src/app/course-table/admin-schedule/admin-schedule.component.ts
web/src/app/course-table/student-schedule/look-all/look-all.component.html
web/src/app/course-table/student-schedule/look-all/look-all.component.ts
web/src/app/course-table/student-schedule/student-schedule.component.html
web/src/app/course-table/student-schedule/student-schedule.component.ts
web/src/app/course-table/teacher-schedule/teacher-schedule.component.html
web/src/app/course-table/teacher-schedule/teacher-schedule.component.ts
web/src/app/entity/course-info.ts

beauty：合并单元格

---

web/src/app/login/login.component.html
web/src/app/login/login.component.ts
web/src/app/personal-center/personal-center.component.html
web/src/app/personal-center/personal-center.component.ts

有个小问题是：小眼睛的图标不可以变化；
个人中心的旧密码不可见，新密码默认不可见，但可以选择可见

181:修改密码的可见性
